apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jira-home
  namespace: siva-test
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 2Gi
